# Site configuration for production
# See default configuration: https://jekyllrb.com/docs/configuration/default

# Server

url: "http://localhost:4000" # change by https://your.domain.name
baseurl: ""

# SEO

title: "Software Engineering Blog - Bob"
description: "Personal blog about software engineering"
author: "Bob"
keywords: "bob,informatics,mathematics,software,engineer"
logo: "/_static/config/img/icon-iphone.png"
lang: "en"

# Articles

paginate: 12
paginate_path: "/blog/articles/page/:num/"
permalink: "/blog/articles/:year/:month/:day/:title:output_ext"

# /!\ Overridden by --drafts command line option (if present force to true)
show_drafts: false

# /!\ Overridden by --unpublished command line option (if present force to true)
unpublished: false

# Specific to project

project:
  blog:
    title: "Software Engineering"
    keywords: [ "Research", "Development / Software", "Algorithm", "Design", "Data", "AI / Machine Learning", "Applied Mathematics", "Computer science", "Web", "Security", "Reliability", "Infrastructure / Hardware", "System", "Methodology", "Business" ]
    logo_header: "/_static/config/img/site-logo.png"
    theme_color: "#383b43"
    menu_items:
      - name: "Blog"
        link: "/blog/"
        tooltip: ""
      - name: "About"
        link: "/about/"
        tooltip: ""
      - name: "🧑🏼‍💻 Source code"
        link: "https://github.com/glegoux/jekyll-tech-blog"
        tooltip: "Explore the source code"
      - name: "🗂️ Documentation"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki"
        tooltip: "Read the documentation"
    socials:
      - name: "LinkedIn"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
        class_icon:  "fab fa-linkedin"
      - name: "Twitter"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
        class_icon: "fab fa-twitter"
      - name: "GitHub"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
        class_icon:  "fab fa-github"
      - name: "SlideShare"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
        class_icon: "fab fa-slideshare"
      - name: "Medium"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
        class_icon: "fab fa-medium"
      - name: "Email"
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
        class_icon:  "fas fa-paper-plane"
    link_status_availability: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
    google_analytics_code: ""
  avatar:
    name: "Bob"
    job: "Software Engineer"
    links:
      github: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
      linkedin: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
      stackoverflow: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
      medium: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
  article:
    comment:
      disqus_code: ""
    source_code:
      url: "https://raw.githubusercontent.com/glegoux/jekyll-tech-blog/main/src/_posts"
    resources:
      url: "https://raw.githubusercontent.com/glegoux/jekyll-tech-blog/main/resources"
    issue:
      url: "https://github.com/glegoux/jekyll-tech-blog/issues"
    edit:
      url: "https://github.com/glegoux/jekyll-tech-blog/edit/main/src/_posts/"
    static:
      url: "https://raw.githubusercontent.com/glegoux/articles-glegoux-com/master/articles"
      image:
        path: "images"
        suffix: ""
    authors:
      bob:
        firstname: "Bob"
        lastname: ""
        job: "Software Engineer"
        company: ""
        follow_link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Configuration"
      glegoux:
        firstname: "Gilles"
        lastname: "LEGOUX"
        job: "Software Engineer"
        company: ""
        follow_link: "https://glegoux.com"
