# Site configuration for production
# See default configuration: https://jekyllrb.com/docs/configuration/default

# Server

url: "https://glegoux.com"
baseurl: ""

# SEO

title: "Software Engineering Blog - Gilles Legoux"
description: "Personal blog about software engineering"
author: "Gilles Legoux"
keywords: "glegoux,Gilles,Legoux,informatics,mathematics,software,engineer"
logo: "/_static/config/img/icon-iphone.png"
lang: "en"

# Articles

paginate: 12
paginate_path: "/blog/articles/page/:num/"
permalink: "/blog/articles/:year/:month/:day/:title:output_ext"

# /!\ Overridden by --drafts command line option (if present force to true)
show_drafts: false

# /!\ Overridden by --unpublished command line option (if present force to true)
unpublished: false

# Specific to project

project:
  blog:
    name_header: "@GillesLegoux (glegoux)"
    logo_header: "/_static/config/img/site-logo.png"
    menu_items:
      - name: "Home"
        link: "/"
        class_icon: "fa fa-home"
      - name: "Blog"
        link: "/blog/"
        class_icon: "fas fa-newspaper"
      - name: "About"
        link: "/about/"
        class_icon: "fas fa-user"
      - name: "Contact"
        link: "/contact/"
        class_icon: "fas fa-address-card"
    title: "Software Engineering"
    keywords: [ "Research", "Development / Software", "Algorithm", "Design", "Data", "AI / Machine Learning", "Applied Mathematics", "Computer science", "Web", "Security", "Reliability", "Infrastructure / Hardware", "System", "Methodology", "Business" ]
    socials:
      - name: "LinkedIn"
        link: "https://www.linkedin.com/in/gilleslegoux"
        class_icon:  "fab fa-linkedin"
      - name: "Twitter"
        link: "https://twitter.com/gilleslegoux"
        class_icon: "fab fa-twitter"
      - name: "GitHub"
        link: "https://github.com/glegoux"
        class_icon:  "fab fa-github"
      - name: "SlideShare"
        link: "https://www.slideshare.net/gilleslegoux"
        class_icon: "fab fa-slideshare"
      - name: "Medium"
        link: "https://medium.com/@glegoux"
        class_icon: "fab fa-medium"
      - name: "Email"
        link: "https://www.glegoux.com/contact/email"
        class_icon:  "fas fa-paper-plane"
    link_status_availability: "http://status.glegoux.com"
    google_analytics_code: "UA-102138582-1"
    disqus_name: "glegoux-com"
    theme_color: "#383b43"
  article:
    source_code:
      url: "https://raw.githubusercontent.com/glegoux/jekyll-blog/develop/src/_posts"
    resources:
      url: "https://github.com/glegoux/articles-glegoux-com/tree/master/articles"
    issue:
      url: "https://github.com/glegoux/jekyll-blog/issues"
    edit:
      url: "https://github.com/glegoux/jekyll-blog/edit/develop/src/_posts/"
    static:
      url: "https://raw.githubusercontent.com/glegoux/articles-glegoux-com/master/articles"
      image:
        path: "images"
        suffix: ""
    authors:
      glegoux:
        firstname: "Gilles"
        lastname: "LEGOUX"
        job: "Software Engineer"
        company: "Criteo"
        follow_link: "https://www.linkedin.com/in/gilleslegoux"
