# Site configuration for production
# See default configuration: https://jekyllrb.com/docs/configuration/default

# Server

url: "https://glegoux.com"
baseurl: ""

# SEO

title: "Software Engineering Blog - Gilles Legoux (glegoux)"
description: "Personal blog about software engineering"
author: "Gilles Legoux"
keywords: "Gilles,Legoux,glegoux,informatics,mathematics,software,engineer"
logo: "/_static/config/img/icon-iphone.png"
lang: "en"

# Articles

paginate: 12
paginate_path: "/blog/articles/page/:num/"
permalink: "/blog/articles/:year/:month/:day/:title:output_ext"

# /!\ Overridden by --drafts command line option (if present force to true)
show_drafts: false

# /!\ Overridden by --unpublished command line option (if present force to true)
unpublished: false

# Specific to project

project:
  blog:
    title: "Software Engineering"
    keywords: [ "Research", "Development / Software", "Algorithm", "Design", "Data", "AI / Machine Learning", "Applied Mathematics", "Computer science", "Web", "Security", "Reliability", "Infrastructure / Hardware", "System", "Methodology", "Business" ]
    logo_header: "/_static/config/img/site-logo.png"
    theme_color: "#383b43"
    menu_items:
      - name: "Home"
        link: "/"
        tooltip: ""
      - name: "Blog"
        link: "/blog/"
        tooltip: ""
      - name: "About"
        link: "/about/"
        tooltip: ""
      - name: "Contact"
        link: "/contact/"
        tooltip: ""
    socials:
      - name: "LinkedIn"
        link: "https://www.linkedin.com/in/gilleslegoux"
        class_icon:  "fab fa-linkedin"
      - name: "Twitter"
        link: "https://twitter.com/gilleslegoux"
        class_icon: "fab fa-twitter"
      - name: "GitHub"
        link: "https://github.com/glegoux"
        class_icon:  "fab fa-github"
      - name: "SlideShare"
        link: "https://www.slideshare.net/gilleslegoux"
        class_icon: "fab fa-slideshare"
      - name: "Medium"
        link: "https://medium.com/@glegoux"
        class_icon: "fab fa-medium"
      - name: "Email"
        link: "https://www.glegoux.com/contact/email"
        class_icon:  "fas fa-paper-plane"
    status_availability:
      link: "https://status.glegoux.com"
    google_analytics_code: "UA-102138582-1"
  avatar:
    name: "Gilles Legoux"
    job: "Senior Software Engineer"
    github:
      link: "https://github.com/glegoux"
    linkedin:
      link: "https://www.linkedin.com/in/gilleslegoux"
    stackoverflow:
      link: "https://stackoverflow.com/users/8071126/glegoux"
    medium:
      link: "https://medium.com/@glegoux"
  article:
    comment:
      disqus_code: "glegoux-com"
    actions:
      source_code:
        link: "https://raw.githubusercontent.com/glegoux/jekyll-blog/glegoux.com/src/_posts"
      resources:
        link: "https://github.com/glegoux/articles-glegoux-com/tree/master/articles"
      edit:
        link: "https://github.com/glegoux/jekyll-tech-blog/edit/glegoux.com/src/_posts/"
      issue:
        link: "https://github.com/glegoux/jekyll-tech-blog/issues"
      help:
        link: "https://github.com/glegoux/jekyll-tech-blog/wiki/Help"
    attachment:
      url: "https://raw.githubusercontent.com/glegoux/articles-glegoux-com/master/articles"
      image:
        path: "images"
        suffix: ""
    authors:
      glegoux:
        firstname: "Gilles"
        lastname: "LEGOUX"
        job: "Senior Software Engineer"
        company: "Criteo"
        follow:
          link: "https://glegoux.com"
