name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: (project) Show environment
        run: |
          echo "Operating System: $(cat /etc/issue.net)"
          echo "Working Directory: $(pwd)"
          echo "User: $(id)"
          echo "Shell: $SHELL"
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1 # use .ruby-version
      - name: (project) Install
        run: |
          echo "** Install ruby dependencies:"
          make install
      - name: (project) Show versions
        run: |
          source ~/.profile
          echo "** Context ecosystem:"
          echo "git version: $(git --version)"
          echo "make version: $(make --version | head -1)"
          echo "bash version: $(bash --version | head -1)"
          echo "** Ruby ecosystem:"
          echo "ruby version: $(ruby --version)"
          echo "bundle version: $(bundle --version)"
          echo "jekyll version: $(jekyll --version 2> /dev/null)"
          echo -e "gem version:\n$(gem list)"
      - name: (project) Build
        run: |
          source ~/.profile
          make build
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: (project) Test
        run: |
          echo "** Install test dependencies:"
          npm install -global stylelint
          sudo apt install jq
          echo "** Show test versions:"
          echo "node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "stylelint version: $(npx stylelint --version)"
          echo "jq version: $(jq --version)"
          echo "** Run tests:"
          make test
